### ISSUE TITLE
Bookmarks limit?

### ISSUE THREAD

**Issue by sergiodicandia** [jparise/stale#11] opened 2023-12-26 17:00 UTC
I'm trying to run stale against my pinboard account, which holds >11,000 bookmarks, but it freezes after a while, always at the same bookmark (which look fine, BTW).
Is there a limit in the number of checked bookmarks?
Thanks in advance

**Comment by jparise** [comment] 2023-12-26 23:29
I'm not aware of any explicit or implicit limits. Does `-v` (verbose) provide any additional detail?

My only guess is that stale uses HTTP `HEAD` requests to check the link URLs, and I wonder if the remote host is doing something unexpected or time-consuming in that case.

You could try changing this line locally to use a `GET` request instead:

https://github.com/jparise/stale/blob/399f1c4ec1b390ff84837b9ef1a8fd48bcc1f93a/stale.py#L65

**Comment by sergiodicandia** [comment] 2023-12-27 16:57
Unfortunately no details, it just hangs.
In a case, it stopped on a cdn link; in others no clues about the reason.
I tried deleting python cache, same result.
Now I changed the line locally as per your suggestion, it stops running on different links (active and apparently normal)

**Comment by jparise** [comment] 2023-12-27 19:38
I just added a few more options that might be useful in this investigation. Let me know if they're helpful.

- `--debug` enables debug-level HTTP connection output
- `--timeout` can be used to specify the HTTP connection timeout (in seconds; defaults to 5)

**Comment by sergiodicandia** [comment] 2023-12-28 12:20
Cool, looks like it was a timeout problem, now it's running fine.
Just a note: I used the -e flag and it deleted a lot of bookmarks (about 3,000): looks like a lot to me, could it be too aggressive? maybe it considers failed logins as errors?
In this case I'll reload a backup and run again without the -e flag, but I'm curious.

Many thanks for your prompt support and the valuable program, really appreciated!

**Comment by jparise** [comment] 2023-12-28 19:17
I just changed the logic to report and skip URLs that time out rather than considering them full errors. I should have done that in the first place. :)

I'll close this issue now that we know the root cause, but please re-open if there's more that we can improve in the script itself.

**Closed by jparise** 2023-12-28 19:17 UTC

**Comment by sergiodicandia** [comment] 2023-12-29 14:34
Sorry to ask again, but it keeps on deleting bookmarks with 403 errors...
That's strange, in line 168 it's explicitly excluded (but I'm not a programmer at all).
Thanks as usual for your support

**Comment by jparise** [comment] 2023-12-29 17:37
I was overlooking an entire error path. 5eff380709a47d7e6171b558f3a38585bdd5a9b3 now applies our "ignore some HTTP client errors (e.g. HTTP 403) consistently.

Thank you for pointing this out!

**Comment by sergiodicandia** [comment] 2023-12-30 12:00
Hi, unfortunately there's still something strange: 404s aren't deleted as expected (while 403s are correctly skipped):
[stale231230.txt](https://github.com/jparise/stale/files/13797925/stale231230.txt)

**Comment by jparise** [comment] 2023-12-30 15:53
You'll need to specify `--delete` if you want the deletion behavior.

**Comment by sergiodicandia** [comment] 2023-12-31 11:19
Of course, I used -d as usual. I also tried with the extended version --delete, same result:
for example, the first link reports a 404 (while the site is alive and responding) and stale won't delete it anyway:

Microsoft Windows [Versione 10.0.22621.2861]
(c) Microsoft Corporation. Tutti i diritti riservati.

C:\Users\sergi\bin\stale>stale.py -t xxx:xxx --delete --timeout 10
[!!] https://csrc.nist.gov/pubs/sp/800/145/final
> HTTP Error 404:
[403] https://twitter.com/heybarsee/status/1640368020949221376
[403] https://platform.openai.com/docs/guides/prompt-engineering
[Timeout] https://www.cwi.it/sicurezza/privacy/fingerprinting-digitale-tracciamento-online-155994
[!!] https://www.manualenuovegenerazioni.it/
> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
[!!] https://geniekeyshop.com/
> <urlopen error [Errno 11001] getaddrinfo failed>
[!!] https://www.salestim.com/microsoft-teams-naming-convention-a-complete-list-of-possibilities-to-improve-your-naming-strategy/
> <urlopen error [Errno 11001] getaddrinfo failed>
[!!] https://www.linkedin.com/pulse/how-combine-space-offered-microsoft-365-family-joseph-s-luo/
> HTTP Error 404: Not Found
[!!] https://www.multcloud.com/mc_project/add_cloud
> HTTP Error 404: Not Found
[!!] https://www.assofacile.it/software-gestione-associazione-come-scegliere-il-tuo-software-gestionale/
> HTTP Error 404: Not Found

**Comment by jparise** [comment] 2023-12-31 21:16
> Of course, I used -d as usual. I also tried with the extended version --delete

My mistake! I missed the `-d` in your logged command line.

> > [!!] https://www.linkedin.com/pulse/how-combine-space-offered-microsoft-365-family-joseph-s-luo/
> > HTTP Error 404: Not Found

This output format makes me wonder if you're using the code I changed yesterday in 41a684e7bab3b64e57955873a48f3e2d2f3a8225. If not, could you try updating to that?

**Comment by sergiodicandia** [comment] 2024-01-03 15:24
You're definitely right, I missed the release. I ran it and it worked as expected, thanks a lot!
To recap, it deletes all 40x errors except 403s, leaving the others where they are, right?
